services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped
  fullstack-api:
    container_name: fullstack-api
    image: ahmadmujtaba200210/fullstack
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  fullstack-frontend-react:
    container_name: frontend-react
    image: ahmadmujtaba200210/fullstack-react
    build:
      dockerfile: Dockerfile
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - fullstack-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:





